
//----------------------------------------------------
// The following code was generated by CUP v0.12joho 20110608
// Sun Jun 15 21:44:11 EDT 2014
//----------------------------------------------------

package bixie.boogie.parser;

/** CUP generated class containing symbol constants. */
public class LexerSymbols {
  /* terminals */
  public static final int error = 0;
  public static final int EOF = 1;
  public static final int TYPE = 2;
  public static final int CONST = 3;
  public static final int FUNCTION = 4;
  public static final int AXIOM = 5;
  public static final int VAR = 6;
  public static final int PROCEDURE = 7;
  public static final int IMPLEMENTATION = 8;
  public static final int FINITE = 9;
  public static final int UNIQUE = 10;
  public static final int COMPLETE = 11;
  public static final int RETURNS = 12;
  public static final int WHERE = 13;
  public static final int ASYNC = 14;
  public static final int FREE = 15;
  public static final int REQUIRES = 16;
  public static final int ENSURES = 17;
  public static final int MODIFIES = 18;
  public static final int INVARIANT = 19;
  public static final int OLD = 20;
  public static final int FORALL = 21;
  public static final int EXISTS = 22;
  public static final int BOOL = 23;
  public static final int INT = 24;
  public static final int REAL = 25;
  public static final int FALSE = 26;
  public static final int TRUE = 27;
  public static final int ASSUME = 28;
  public static final int ASSERT = 29;
  public static final int HAVOC = 30;
  public static final int CALL = 31;
  public static final int IF = 32;
  public static final int THEN = 33;
  public static final int ELSE = 34;
  public static final int WHILE = 35;
  public static final int BREAK = 36;
  public static final int RETURN = 37;
  public static final int GOTO = 38;
  public static final int YIELD = 39;
  public static final int PAR = 40;
  public static final int COMMA = 41;
  public static final int COLON = 42;
  public static final int SEMI = 43;
  public static final int COLONEQUALS = 44;
  public static final int EQUALS = 45;
  public static final int LPAR = 46;
  public static final int RPAR = 47;
  public static final int LBKT = 48;
  public static final int RBKT = 49;
  public static final int LBRC = 50;
  public static final int RBRC = 51;
  public static final int LANG = 52;
  public static final int RANG = 53;
  public static final int VBAR = 54;
  public static final int LESS = 55;
  public static final int GREATER = 56;
  public static final int LTEQ = 57;
  public static final int GTEQ = 58;
  public static final int NEQ = 59;
  public static final int EQ = 60;
  public static final int PARTORDER = 61;
  public static final int PLUS = 62;
  public static final int MINUS = 63;
  public static final int TIMES = 64;
  public static final int DIVIDE = 65;
  public static final int MOD = 66;
  public static final int QSEP = 67;
  public static final int NOT = 68;
  public static final int OR = 69;
  public static final int AND = 70;
  public static final int IMPLIES = 71;
  public static final int IFF = 72;
  public static final int EXPLIES = 73;
  public static final int CONCAT = 74;
  public static final int EXTENDS = 75;
  public static final int BVTYPE = 76;
  public static final int NUMBER = 77;
  public static final int REALNUMBER = 78;
  public static final int BITVECTOR = 79;
  public static final int ID = 80;
  public static final int ATTR_STRING = 81;
}

